### ISSUE TITLE
Thiết kế hệ thống

### ISSUE THREAD

**Issue by sownt** [sownt/TheOctoFood#2]
Yêu cầu đối với báo cáo giữa kỳ:
- [x] Phát biểu bài toán
    - [x] Nêu bài toán
    - [x] Đặc điểm bài toán
    - [x] Các vấn đề chính cần giải quyết
- [x] Phương pháp thực hiện
    - [x] Cách giải quyết các vấn đề
    - [x] Các thư viện, kỹ thuật, công nghệ được sử dựng
    - [x] Xây dựng dữ liệu như thế nào

**Comment by doanhtuyettt** [comment]
#### Báo cáo giữa kì:
**1. Nêu ra bài toán :**
- Nêu ra bài toán của đề tài là gì?
  - Xây dựng Website đặt đồ ăn , giải quyết tối ưu hoá quá trình quản lý bán hàng và đáp ứng nhu cầu đặt đồ ăn, mua lương thực online do tình hình ảnh hưởng của dịch Co-vid19:
     - Modul sản phẩm
     - Modul quảng cáo
     - Modul tìm kiếm thông tin
     - Modul giỏ hàng
     - Modul trợ giúp
- Các đặc điểm của bài toán
- Các vấn đề chính cần giải quyết :
   - Việc đặt hàng
   - Quản lý đơn hàng
   - Quản lý khách hàng
   - Xem thông tin đơn hành
   - ....
**2. Phương pháp thực hiện:**
- Các cách giải quyết các vấn đề của bài toán

- Các thư viện, kỹ thuật, công nghệ được lựa chọn sử dụng là gì?
   - Front-end : Bootstrap
   - Back-end : python, Django framework
   - Sử dụng Github quản lý source code 

- Xây dựng dữ liệu thế nào?
  - _DL đầu vào :_
      - Nhà cung cấp
         - Id nhà cung cấp
         - Tên nhà cung cấp
         - Địa chỉ nhà cung cấp
         - Sđt
         - Email
         - Website
         
      - Sản phẩm
         - ID sản phẩm
         - Tên sản phẩm
         - Id loại sản phẩm
         - Hình ảnh sản phẩm
         - Số lượng sản phẩm còn
         - Giá bán
         - Mô tả sản phẩm

  - Ngân hàng
     - ID ngân hàng
     - Tên ngân hàng
     - Mã khách hàng
     - Tên tài khoản
     - Số mã pin
     - Số dư tài khoản
     
  - Chương trình khuyến mãi
     - Id khuyến mãi
     - Id sản phẩm
     - Giá cũ
     - Giá mới
     - Thời gian bắt đầu
     - Thời gian kết thúc
     - Quà tặng kèm
     
  - Người dùng
     - ID khách hàng
     - Tên khách hàng
     - Tên đăng nhập
     - Mật khẩu
     - Giới tính
     - Tuổi
     - Chứng minh thư
     - Địa chỉ

- _DL đầu ra :_
  - Đơn hàng
     - Id đơn hàng
     - Id sản phẩm
     - Số lượng sản phẩm
     - Id giao dịch
     - Tổng số tiền
     - Trạng thái thanh toán
     - Ngày dặt hàng

**Comment by doanhtuyettt** [comment]
**2. Phương pháp thực hiện:**
- Các cách giải quyết các vấn đề của bài toán

- Các thư viện, kỹ thuật, công nghệ được lựa chọn sử dụng là gì?
   - Front-end : Bootstrap
   - Back-end : python, Django framework
   - Sử dụng Github quản lý source code

**Comment by doanhtuyettt** [comment]
- Xây dựng dữ liệu thế nào?
  - _DL đầu vào :_
      - Nhà cung cấp
         - Id nhà cung cấp
         - Tên nhà cung cấp
         - Địa chỉ nhà cung cấp
         - Sđt
         - Email
         - Website
         
      - Sản phẩm
         - ID sản phẩm
         - Tên sản phẩm
         - Id loại sản phẩm
         - Hình ảnh sản phẩm
         - Số lượng sản phẩm còn
         - Giá bán
         - Mô tả sản phẩm

      - Ngân hàng
        - ID ngân hàng
        - Tên ngân hàng
        - Mã khách hàng
        - Tên tài khoản
        - Số mã pin
        - Số dư tài khoản
     
      - Chương trình khuyến mãi
        - Id khuyến mãi
        - Id sản phẩm
        - Giá cũ
        - Giá mới
        - Thời gian bắt đầu
        - Thời gian kết thúc
        - Quà tặng kèm
     
     - Người dùng
       - ID khách hàng
       - Tên khách hàng
       - Tên đăng nhập
       - Mật khẩu
       - Giới tính
       - Tuổi
       - Chứng minh thư
       - Địa chỉ

  - _DL đầu ra :_
     - Đơn hàng
        - Id đơn hàng
        - Id sản phẩm
        - Số lượng sản phẩm
        - Id giao dịch
        - Tổng số tiền
        - Trạng thái thanh toán
        - Ngày dặt hàng

**Comment by doanhtuyettt** [comment]
DL đầu vào :
| Nhà cung cấp | Sản phẩm | Ngân hàng | Chương trình khuyến mãi | Người dùng |
| --- | --- | --- | --- | --- |
| Id nhà cung cấp | ID sản phẩm | ID ngân hàng | Id khuyến mãi | ID khách hàng |
| Tên nhà cung cấp | Tên sản phẩm | Tên ngân hàng | Id sản phẩm | Tên khách hàng |
| Địa chỉ nhà cung cấp | Id loại sản phẩm | Mã khách hàng | Giá cũ | Tên đăng nhập |
| Sđt | Hình ảnh sản phẩm | Tên tài khoản | Giá mới | Mật khẩu |
| Email | Số lượng sản phẩm còn | Số mã pin | Thời gian bắt đầu | Giới tính |
| Website | Giá bán | Số dư tài khoản | Thời gian kết thúc | Tuổi |
| | Mô tả sản phẩm | | Quà tặng kèm | Chứng minh thư |
| | | | | Địa chỉ |

**Comment by doanhtuyettt** [comment]
_DL đầu ra :_
| Đơn hàng |
| --- |
| ID đơn hàng |
| ID sản phẩm |
| Số lượng sản phẩm |
| ID giao dịch |
| Tổng số tiền |
| Trạng thái thanh toán |
| Ngày đặt hàng |
