### ISSUE TITLE
Viết tài liệu hướng dẫn chạy project

### ISSUE THREAD

**Issue by sownt** [sownt/TheOctoFood#20]

**Comment by doanhtuyettt** [comment]
### 1. Cài đặt môi trường ảo cho Django: ###
- Kiểm tra phiên bản *Python* đang cài đặt : 
 >$ python3 –V 
- Tạo môi trường ảo :
>$ pip install virtualenv
>$ virtualenv –p python3 .
- Kích hoạt môi trường ảo :
>$ source bin/activate
- Khi đã vào môi trường ảo , cài đặt *Django*:
>$ pip install django
// chờ đợi cho cài đặt hoàn tất
